//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGI_Documentos_Adjuntos
    {
        public int id_doc_adj { get; set; }
        public int id_tdoc_adj { get; set; }
        public int id_tramitetarea { get; set; }
        public string tdoc_adj_detalle { get; set; }
        public byte[] documento { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
    }
}
