//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.GestionTramite.Tareas.Transferencias
{


    public partial class Revision_Firma_Disposicion
    {

        /// <summary>
        /// ucCabecera control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGI.GestionTramite.Controls.ucCabecera ucCabecera;

        /// <summary>
        /// ucTitulares control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGI.GestionTramite.Controls.Transferencias.ucTitulares ucTitulares;

        /// <summary>
        /// ucListaDocumentos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGI.GestionTramite.Controls.ucListaDocumentosv1 ucListaDocumentos;

        /// <summary>
        /// ucPreviewDocumentos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGI.GestionTramite.Controls.ucPreviewDocumentos ucPreviewDocumentos;

        /// <summary>
        /// hid_id_solicitud control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hid_id_solicitud;

        /// <summary>
        /// hid_id_tramitetarea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hid_id_tramitetarea;

        /// <summary>
        /// ucListaObservacionesAnteriores control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGI.GestionTramite.Controls.ucListaObservacionesAnteriores ucListaObservacionesAnteriores;

        /// <summary>
        /// ucListaObservacionesAnterioresv1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGI.GestionTramite.Controls.ucListaObservacionesAnterioresv1 ucListaObservacionesAnterioresv1;

        /// <summary>
        /// ucProcesosSADE control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGI.GestionTramite.Controls.ucProcesosSADEv1 ucProcesosSADE;

        /// <summary>
        /// ucObservacionesTarea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGI.GestionTramite.Controls.ucObservacionesTarea ucObservacionesTarea;

        /// <summary>
        /// ucResultadoTarea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGI.GestionTramite.Controls.ucResultadoTarea ucResultadoTarea;
    }
}
