//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.GestionTramite.Tareas.Transferencias {
    
    
    public partial class Verificacion_AVH {
        
        /// <summary>
        /// ucCabecera control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGI.GestionTramite.Controls.ucCabecera ucCabecera;
        
        /// <summary>
        /// ucListaDocumentos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGI.GestionTramite.Controls.ucListaDocumentosv1 ucListaDocumentos;
        
        /// <summary>
        /// hid_id_solicitud control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hid_id_solicitud;
        
        /// <summary>
        /// hid_id_tramitetarea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hid_id_tramitetarea;
        
        /// <summary>
        /// ucListaObservacionesAnteriores control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGI.GestionTramite.Controls.ucListaObservacionesAnteriores ucListaObservacionesAnteriores;
        
        /// <summary>
        /// ucListaObservacionesAnterioresv1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGI.GestionTramite.Controls.ucListaObservacionesAnterioresv1 ucListaObservacionesAnterioresv1;
        
        /// <summary>
        /// ucSGI_DocumentoAdjunto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGI.GestionTramite.Controls.ucSGI_DocumentoAdjunto ucSGI_DocumentoAdjunto;
        
        /// <summary>
        /// ucObservacionesTarea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGI.GestionTramite.Controls.ucObservacionesTarea ucObservacionesTarea;
        
        /// <summary>
        /// ucProcesosSADE control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGI.GestionTramite.Controls.ucProcesosSADEv1 ucProcesosSADE;
        
        /// <summary>
        /// ucResultadoTarea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGI.GestionTramite.Controls.ucResultadoTarea ucResultadoTarea;
    }
}
